name: "DevSecOps Terraform CI/CD"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Pipeline de Infraestrutura"
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Baixar o Código
        uses: actions/checkout@v4

      - name: 🔐 Colocar o Crachá da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: 🛠️ Instalar o Terraform
        uses: hashicorp/setup-terraform@v3

      - name: ⚙️ Terraform Init
        run: terraform init

      - name: 📝 Terraform Plan
        run: terraform plan -out=tfplan

      - name: 🚀 Terraform Apply
        run: terraform apply -auto-approve tfplan