name: "DevSecOps Terraform CI/CD"

# O gatilho: roda o robô sempre que fizermos um push na branch main
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Pipeline de Infraestrutura"
    runs-on: ubuntu-latest # O computador que o GitHub vai nos emprestar

    steps:
      - name: ⬇️ Baixar o Código
        uses: actions/checkout@v4

      - name: 🔐 Colocar o Crachá da AWS (Pegando do Cofre)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: 🛠️ Instalar o Terraform
        uses: hashicorp/setup-terraform@v3

      - name: ⚙️ Terraform Init
        run: terraform init

      - name: 🔍 Verificação de Código (Segurança/Padrão)
        run: terraform fmt -check

      - name: 📝 Terraform Plan
        run: terraform plan -out=tfplan

      - name: 🚀 Terraform Apply
        run: terraform apply -auto-approve tfplan